# Generated by Django 4.1.4 on 2023-01-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_features_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuress', to='devices.device'),
        ),
    ]
